# Site settings
title: Proggramming with R, Python and Ruby
email: lopezrj@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Notes about programming in several languages.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lopezrj.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
